/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#181c1d',
        'background': '#f7fafb',
        'surface-tint': '#416743',
        'inverse-on-surface': '#eef1f2',
        'surface-container': '#ebeeef',
        'surface-dim': '#d7dadb',
        'primary-fixed': '#c2eec0',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'surface-container-low': '#f1f4f5',
        'on-surface-variant': '#424941',
        'primary': '#416743',
        'primary-fixed-dim': '#a7d1a5',
        'on-surface': '#181c1d',
        'error-container': '#ffdad6',
        'tertiary': '#586152',
        'error': '#ba1a1a',
        'secondary-container': '#e7e2d9',
        'surface-container-high': '#e6e9ea',
        'inverse-primary': '#a7d1a5',
        'on-primary-fixed-variant': '#294f2d',
        'on-tertiary-container': '#2d3629',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#67645d',
        'inverse-surface': '#2d3132',
        'secondary-fixed-dim': '#cac6be',
        'surface-variant': '#e0e3e4',
        'surface-bright': '#f7fafb',
        'on-secondary-fixed': '#1d1c16',
        'primary-container': '#7da67d',
        'outline-variant': '#c2c8be',
        'on-primary-fixed': '#002107',
        'on-primary-container': '#153b1c',
        'tertiary-fixed-dim': '#c0cab7',
        'on-tertiary-fixed-variant': '#40493b',
        'on-secondary': '#ffffff',
        'outline': '#727970',
        'surface-container-highest': '#e0e3e4',
        'surface': '#f7fafb',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#dce6d2',
        'on-tertiary-fixed': '#151e12',
        'secondary-fixed': '#e7e2d9',
        'on-secondary-fixed-variant': '#494740',
        'tertiary-container': '#959f8e',
        'on-error-container': '#93000a',
        'secondary': '#615e57',
        'beige': '#F5F5F0',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'h1': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'h2': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        'btn': ['16px', { lineHeight: '1', fontWeight: '600' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      maxWidth: {
        container: '1280px',
      },
      spacing: {
        gutter: '24px',
        section: '80px',
      },
    },
  },
  plugins: [],
};
